name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          # Inject the API key as an environment variable in your JavaScript code
          echo "window.API_KEY='${{ secrets.OPEN_AI_API }}';" > config/env.js
          # Build your project
          npm run build
        env:
          API_KEY: ${{ secrets.OPEN_AI_API }}

