name: Build and Deploy

on:
  push:
    branches:
      - master
env:
  OPEN_AI_API: ${{ secrets.OPEN_AI_API }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug API Key Secret
        run: |
          echo "API key secret: ${{ secrets.OPEN_AI_API }}"
          
      - name: Checkout code
        uses: actions/checkout@v2